Removed insserv call to xinetd. bnc#1026027
- xinetd was ported to systemd some time ago already (at least for whole
  SLE-12 product line)
- innserv is being removed as soon as possible. Yast is requested to
  relax its dependency on insserv

diff --git a/tools/setup_network_scanner_config b/tools/setup_network_scanner_config
--- a/tools/setup_network_scanner_config
+++ b/tools/setup_network_scanner_config
@@ -71,14 +71,6 @@ fi
 # and do the appropriate stuff regarding the xinetd:
 if [ -n "$SANED_CONFIG" ]
 then sed -i -e 's/^.*disable.*$/\tdisable     = no/' $XINETD_CONFIG_FILE || { echo "Failed to enable saned in $XINETD_CONFIG_FILE" 1>&2 ; exit 6 ; }
-     if test -e $XINETD_INIT_SCRIPT
-     then if $XINETD_INIT_SCRIPT status &>/dev/null
-          then $XINETD_INIT_SCRIPT reload || { echo "Failed to reload xinetd" 1>&2 ; exit 7 ; }
-          else $XINETD_INIT_SCRIPT start || { echo "Failed to start xinetd" 1>&2 ; exit 8 ; }
-               insserv xinetd || { echo "Failed to insserv xinetd" 1>&2 ; exit 9 ; }
-          fi
-          exit 0
-     fi
      if test -e $XINETD_SYSTEMD_UNIT_FILE
      then if systemctl --quiet is-active $XINETD_SYSTEMD_UNIT && systemctl --quiet is-enabled $XINETD_SYSTEMD_UNIT
           then systemctl --quiet reload $XINETD_SYSTEMD_UNIT || { echo "Failed to reload xinetd" 1>&2 ; exit 7 ; }
@@ -87,22 +79,16 @@ then sed -i -e 's/^.*disable.*$/\tdisable     = no/' $XINETD_CONFIG_FILE || { ec
           fi
           exit 0
      fi
-     echo "Cannot reload or start and enable xinetd (neither $XINETD_INIT_SCRIPT nor $XINETD_SYSTEMD_UNIT_FILE)" 1>&2
+     echo "Cannot reload or start and enable xinetd." 1>&2
      exit 11
 else sed -i -e 's/^.*disable.*$/\tdisable     = yes/' $XINETD_CONFIG_FILE || { echo "Failed to disable saned in $XINETD_CONFIG_FILE" 1>&2 ; exit 10 ; }
-     if test -e $XINETD_INIT_SCRIPT
-     then if $XINETD_INIT_SCRIPT status &>/dev/null
-          then $XINETD_INIT_SCRIPT reload || { echo "Failed to reload xinetd" 1>&2 ; exit 7 ; }
-          fi
-          exit 0
-     fi
      if test -e $XINETD_SYSTEMD_UNIT_FILE
      then if systemctl --quiet is-active $XINETD_SYSTEMD_UNIT
           then systemctl --quiet reload $XINETD_SYSTEMD_UNIT || { echo "Failed to reload xinetd" 1>&2 ; exit 7 ; }
           fi
           exit 0
      fi
-     echo "Cannot reload xinetd (neither $XINETD_INIT_SCRIPT nor $XINETD_SYSTEMD_UNIT_FILE)" 1>&2
+     echo "Cannot reload xinetd." 1>&2
      exit 11
 fi
 
