- V 2.13.1 - Added support for SUSE Firewall.
svn path=/trunk/scanner/; revision=26285

diff --git a/tools/setup_network_scanner_config b/tools/setup_network_scanner_config
--- a/tools/setup_network_scanner_config
+++ b/tools/setup_network_scanner_config
@@ -22,21 +22,23 @@ DEACTIVATE_BACKEND=${0%/*}/deactivate_scanner_backend
 XINETD_CONFIG_FILE="/etc/xinetd.d/sane-port"
 XINETD_INIT_SCRIPT="/etc/init.d/xinetd"
 
+# Function to remove old entries and append new entries to a SANE config file:
+ReWrite()
+{ # Remove all non-comment lines:
+  sed -i -e '/^[^#]/d' $1
+  # Remove all empty lines:
+  sed -i -e '/^[[:space:]]*$/d' $1
+  # Append the new config lines if "$2" is not the empty string:
+  if [ -n "$2" ]
+  then echo "$2" | tr -d '[:space:]' | tr -s ',' '\n' >>$1 || { echo "Failed to set '$2' in $1" 1>&2 ; return 1 ; }
+  fi
+}
+
 # Write the NET_BACKEND_CONFIG into the NET_BACKEND_CONFIG_FILE:
-# Remove all non-comment lines:
-sed -i -e '/^[^#]/d' $NET_BACKEND_CONFIG_FILE
-# Append the new config lines if "$NET_BACKEND_CONFIG" is not the empty string:
-if [ -n "$NET_BACKEND_CONFIG" ]
-then echo "$NET_BACKEND_CONFIG" | tr -d '[:space:]' | tr -s ',' '\n' >>$NET_BACKEND_CONFIG_FILE || { echo "Failed to write the new config into $NET_BACKEND_CONFIG_FILE" 1>&2 ; exit 2 ; }
-fi
+ReWrite "$NET_BACKEND_CONFIG_FILE" "$NET_BACKEND_CONFIG" || exit 2
 
 # Write the SANED_CONFIG into the SANED_CONFIG_FILE:
-# Remove all non-comment lines:
-sed -i -e '/^[^#]/d' $SANED_CONFIG_FILE
-# Append the new config lines if "$SANED_CONFIG" is not the empty string:
-if [ -n "$SANED_CONFIG" ] 
-then echo "$SANED_CONFIG" | tr -d '[:space:]' | tr -s ',' '\n' >>$SANED_CONFIG_FILE || { echo "Failed to write the new config into $SANED_CONFIG_FILE" 1>&2 ; exit 3 ; }
-fi
+ReWrite "$SANED_CONFIG_FILE" "$SANED_CONFIG" || exit 3
 
 # Activate the net backend if "$NET_BACKEND_CONFIG" is not the empty string
 # otherwise deactivate the net backend:
@@ -48,13 +50,13 @@ fi
 # Enable the saned if "$SANED_CONFIG" is not the empty string otherwise disable the saned
 # and do the appropriate stuff regarding the xinetd:
 if [ -n "$SANED_CONFIG" ]
-then sed -i -e 's/^.*disable.*$/\tdisable     = no/' $XINETD_CONFIG_FILE || { echo "Failed to enable the saned in $XINETD_CONFIG_FILE" 1>&2 ; exit 6 ; }
+then sed -i -e 's/^.*disable.*$/\tdisable     = no/' $XINETD_CONFIG_FILE || { echo "Failed to enable saned in $XINETD_CONFIG_FILE" 1>&2 ; exit 6 ; }
      if $XINETD_INIT_SCRIPT status &>/dev/null
      then $XINETD_INIT_SCRIPT reload || { echo "Failed to reload xinetd" 1>&2 ; exit 7 ; }
      else $XINETD_INIT_SCRIPT start || { echo "Failed to start xinetd" 1>&2 ; exit 8 ; }
           insserv xinetd || { echo "Failed to insserv xinetd" 1>&2 ; exit 9 ; }
      fi
-else sed -i -e 's/^.*disable.*$/\tdisable     = yes/' $XINETD_CONFIG_FILE || { echo "Failed to disable the saned in $XINETD_CONFIG_FILE" 1>&2 ; exit 10 ; }
+else sed -i -e 's/^.*disable.*$/\tdisable     = yes/' $XINETD_CONFIG_FILE || { echo "Failed to disable saned in $XINETD_CONFIG_FILE" 1>&2 ; exit 10 ; }
      if $XINETD_INIT_SCRIPT status &>/dev/null
      then $XINETD_INIT_SCRIPT reload || { echo "Failed to reload xinetd" 1>&2 ; exit 7 ; }
      fi
