- V 2.13.6 - Fixed test_scanner_backend and setup_ptal_scanner_service. - Changed SetUsbScannerAccessPermissions() to write at least   the comment how to create entries in .../80-scanner.fdi
svn path=/trunk/scanner/; revision=27102

diff --git a/tools/setup_ptal_scanner_service b/tools/setup_ptal_scanner_service
--- a/tools/setup_ptal_scanner_service
+++ b/tools/setup_ptal_scanner_service
@@ -24,22 +24,26 @@ MAXIMUM_WAIT="60"
 # As a signal is processed not until a "sleep" has finished,
 # it is crucial not to do simply "sleep $MAXIMUM_WAIT"
 # but to do "for i in $( seq $MAXIMUM_WAIT ) ; do sleep 1 ; done"
-# because otherwise it would wait in any case until "sleep $MAXIMUM_WAIT" has finished.
+# otherwise it would wait in any case until "sleep $MAXIMUM_WAIT" has finished.
 if [ -x /usr/sbin/ptal-init ]
-then ( for i in $( seq $MAXIMUM_WAIT ) ; do sleep 1 ; done ; killall -9 -v -q ptal-init ) &
+then ( for i in $( seq $MAXIMUM_WAIT ) ; do sleep 1 ; done ; killall -9 ptal-init &>/dev/null ) &
      timebombPID=$!
      ptal-init setup-usb &>/dev/null || { echo "failed: ptal-init setup-usb" 1>&2 ; exit 2 ; }
+     # If the timebomb is still running, ptal-init has finished
+     # and killing the timebomb will be successful.
+     if kill -9 $timebombPID &>/dev/null
+     then # Setup the ptal service:
+          if [ -x /etc/init.d/ptal ]
+          then insserv ptal || { echo "failed: insserv ptal" 1>&2 ; exit 4 ; }
+               /etc/init.d/ptal restart || { echo "failed: /etc/init.d/ptal restart" 1>&2 ; exit 5 ; }
+          else echo "cannot execute /etc/init.d/ptal" 1>&2
+               exit 3
+          fi
+     else echo -e "\nAborted ptal-init after $MAXIMUM_WAIT seconds timeout." 1>&2
+          exit 6
+     fi
 else echo "cannot execute /usr/sbin/ptal-init" 1>&2
      exit 1
-fi
-kill -9 $timebombPID
-
-# Setup the ptal service:
-if [ -x /etc/init.d/ptal ] 
-then insserv ptal || { echo "failed: insserv ptal" 1>&2 ; exit 4 ; }
-     /etc/init.d/ptal restart || { echo "failed: /etc/init.d/ptal restart" 1>&2 ; exit 5 ; }
-else echo "cannot execute /etc/init.d/ptal" 1>&2
-     exit 3
 fi
 
 exit 0
diff --git a/tools/test_scanner_backend b/tools/test_scanner_backend
--- a/tools/test_scanner_backend
+++ b/tools/test_scanner_backend
@@ -14,16 +14,24 @@ BACKEND="$1"
 [ -z "$BACKEND" ] && { echo -en "\nUsage:\n$MY_NAME backend\n" 1>&2 ; exit 1 ; }
 
 MAXIMUM_WAIT="30"
+# The exit code of "scanimage -d $BACKEND -T" is needed as exit code of this script.
+# Therefore this command must run in the foreground.
+# Therefore a simple time bomb background process is started before it.
+# This time bomb background process process is normally killed at the end.
+# As a signal is processed not until a "sleep" has finished,
+# it is crucial not to do simply "sleep $MAXIMUM_WAIT"
+# but to do "for i in $( seq $MAXIMUM_WAIT ) ; do sleep 1 ; done"
+# otherwise it would wait in any case until "sleep $MAXIMUM_WAIT" has finished.
 if [ -x /usr/bin/scanimage ]
-then scanimage -d $BACKEND -T &
-     scanimagePID=$!
-     for i in $( seq $MAXIMUM_WAIT )
-     do ps $scanimagePID &>/dev/null || break
-        sleep 1
-     done
-     if ps $scanimagePID &>/dev/null
-     then kill -9 $scanimagePID &>/dev/null
-          echo "Aborted scanimage after $MAXIMUM_WAIT seconds timeout." 1>&2
+then ( for i in $( seq $MAXIMUM_WAIT ) ; do sleep 1 ; done ; killall -9 scanimage &>/dev/null ) &
+     timebombPID=$!
+     scanimage -d $BACKEND -T
+     scanimageEXIT=$?
+     # If the timebomb is still running, scanimage has finished
+     # and killing the timebomb will be successful.
+     if kill -9 $timebombPID &>/dev/null
+     then exit $scanimageEXIT
+     else echo -e "\nAborted scanimage after $MAXIMUM_WAIT seconds timeout." 1>&2
           exit 3
      fi
 else 
