enhancement for /usr/lib/YaST2/bin/setup_network_scanner_config that provides additional support for systemd (bnc#859353)

diff --git a/tools/setup_network_scanner_config b/tools/setup_network_scanner_config
--- a/tools/setup_network_scanner_config
+++ b/tools/setup_network_scanner_config
@@ -1,6 +1,6 @@
 #! /bin/bash
 
-# Johannes Meixner <jsmeix@suse.de>, 2004, 2005, 2006, 2007, 2008, 2010
+# Johannes Meixner <jsmeix@suse.de>, 2004, 2005, 2006, 2007, 2008, 2010, 2014
 #
 # Copyright (c) 2010 Novell, Inc.
 # All Rights Reserved.
@@ -39,6 +39,8 @@ ACTIVATE_BACKEND=${0%/*}/activate_scanner_backend
 DEACTIVATE_BACKEND=${0%/*}/deactivate_scanner_backend
 XINETD_CONFIG_FILE="/etc/xinetd.d/sane-port"
 XINETD_INIT_SCRIPT="/etc/init.d/xinetd"
+XINETD_SYSTEMD_UNIT="xinetd.service"
+XINETD_SYSTEMD_UNIT_FILE="/usr/lib/systemd/system/$XINETD_SYSTEMD_UNIT"
 
 # Function to remove old entries and append new entries to a SANE config file:
 ReWrite()
@@ -69,15 +71,39 @@ fi
 # and do the appropriate stuff regarding the xinetd:
 if [ -n "$SANED_CONFIG" ]
 then sed -i -e 's/^.*disable.*$/\tdisable     = no/' $XINETD_CONFIG_FILE || { echo "Failed to enable saned in $XINETD_CONFIG_FILE" 1>&2 ; exit 6 ; }
-     if $XINETD_INIT_SCRIPT status &>/dev/null
-     then $XINETD_INIT_SCRIPT reload || { echo "Failed to reload xinetd" 1>&2 ; exit 7 ; }
-     else $XINETD_INIT_SCRIPT start || { echo "Failed to start xinetd" 1>&2 ; exit 8 ; }
-          insserv xinetd || { echo "Failed to insserv xinetd" 1>&2 ; exit 9 ; }
+     if test -e $XINETD_INIT_SCRIPT
+     then if $XINETD_INIT_SCRIPT status &>/dev/null
+          then $XINETD_INIT_SCRIPT reload || { echo "Failed to reload xinetd" 1>&2 ; exit 7 ; }
+          else $XINETD_INIT_SCRIPT start || { echo "Failed to start xinetd" 1>&2 ; exit 8 ; }
+               insserv xinetd || { echo "Failed to insserv xinetd" 1>&2 ; exit 9 ; }
+          fi
+          exit 0
      fi
+     if test -e $XINETD_SYSTEMD_UNIT_FILE
+     then if systemctl --quiet is-active $XINETD_SYSTEMD_UNIT && systemctl --quiet is-enabled $XINETD_SYSTEMD_UNIT
+          then systemctl --quiet reload $XINETD_SYSTEMD_UNIT || { echo "Failed to reload xinetd" 1>&2 ; exit 7 ; }
+          else systemctl --quiet start $XINETD_SYSTEMD_UNIT || { echo "Failed to start xinetd" 1>&2 ; exit 8 ; }
+               systemctl --quiet enable $XINETD_SYSTEMD_UNIT || { echo "Failed to enable xinetd" 1>&2 ; exit 9 ; }
+          fi
+          exit 0
+     fi
+     echo "Cannot reload or start and enable xinetd (neither $XINETD_INIT_SCRIPT nor $XINETD_SYSTEMD_UNIT_FILE)" 1>&2
+     exit 11
 else sed -i -e 's/^.*disable.*$/\tdisable     = yes/' $XINETD_CONFIG_FILE || { echo "Failed to disable saned in $XINETD_CONFIG_FILE" 1>&2 ; exit 10 ; }
-     if $XINETD_INIT_SCRIPT status &>/dev/null
-     then $XINETD_INIT_SCRIPT reload || { echo "Failed to reload xinetd" 1>&2 ; exit 7 ; }
+     if test -e $XINETD_INIT_SCRIPT
+     then if $XINETD_INIT_SCRIPT status &>/dev/null
+          then $XINETD_INIT_SCRIPT reload || { echo "Failed to reload xinetd" 1>&2 ; exit 7 ; }
+          fi
+          exit 0
      fi
+     if test -e $XINETD_SYSTEMD_UNIT_FILE
+     then if systemctl --quiet is-active $XINETD_SYSTEMD_UNIT
+          then systemctl --quiet reload $XINETD_SYSTEMD_UNIT || { echo "Failed to reload xinetd" 1>&2 ; exit 7 ; }
+          fi
+          exit 0
+     fi
+     echo "Cannot reload xinetd (neither $XINETD_INIT_SCRIPT nor $XINETD_SYSTEMD_UNIT_FILE)" 1>&2
+     exit 11
 fi
 
 exit 0
